### PR TITLE
Russian translation improvements

### PR DESCRIPTION
**Pull request by Felix14-v2**
Phrases now correspond to the official Minecraft translation.

### CODE REVIEW

**Comment by florensie** [comment]
@Romz24 I'd like your input on this if you don't mind ;)

**Comment by Romz24** [comment]
The translation fix looks good. I think it can be added, the translation is correct.

**Comment by Felix14-v2** [comment]
You can verify the correctness of the translation by simply setting russian language in the game settings:

image
image

The existing translation is a transliteration of English (спавн = spawn) and an outdated translation from old versions of minecraft (Зачарованная = Чародейская (just different forms) = Enchanted).

**Comment by florensie** [comment]
Thanks!

**Pull request merged**
